GET https://example.com/comments/1 HTTP/1.1

leagueId: ldemf9yvkjpcfa5w

###  Test Get:
GET http://localhost:35580/api/Loans HTTP/1.1


###  Test Get by ID: 1
GET http://localhost:35580/api/Loans/1 HTTP/1.1

###  Test Get by ID: 2
GET http://localhost:35580/api/Loans/2 HTTP/1.1

###  Test Get by ID: 3
GET http://localhost:35580/api/Loans/3 HTTP/1.1


###  Test POST
POST http://localhost:35580/api/Loans/ HTTP/1.1
{
  "id": 4,
  "outstandingAmtCurrent": 4000.00,
  "intRateCurrent": 4.2585,
  "remainingTerm": 456,
  "monthlyPrincipalPayment": 4000.0
}